import car from "../../assets/Images/car.png";
const All_Product = [
  {
    name: "Bugatti",
    color: "blue",
    info: "BRWON NEW BUGATTI AND TOP-EVERYR,YOU GET THE BEST.TRY YOUR LUCK",
    price: 95.99,
    img: car,
    location: "united kingdom",
    caption: "Best rate ",
    phoneNumber: "08132703549",
  },
  {
    name: "Venza",
    color: "blue",
    info: "lorum dghjg djhge duygeruu4ygcd wkeugu wgwerggwe deutkc ",
    price: 95.99,
    img: car,
    location: "lagos state",
  },
  {
    name: "Wagon",
    color: "blue",
    info: "lorum dghjg djhge duygeru 3u4ygcd wkeugu wgwerggwe deutkc ",
    price: 95.99,
    img: car,
    location: "abuja",
  },
  {
    name: "Boomer",
    color: "blue",
    info: "lorum dghjg djhge duygeru 3u4ygcd wkeugu wgwerggwe deutkc ",
    price: 95.99,
    img: car,
    location: "lagos",
  },
  {
    name: "car",
    color: "blue",
    info: "lorum dghjg djhge duygeru 3u4ygcd wkeugu wgwerggwe deutkc ",
    price: 95.99,
    img: car,
    location: "lagos",
  },
  {
    name: "Bugatti",
    color: "blue",
    info: "lorum dghjg djhge duygeru 3u4ygcd wkeugu wgwerggwe deutkc ",
    price: 95.99,
    img: car,
    location: "united kingdom",
    caption: "Best rate ",
    phoneNumber: "08132703549",
  },
  {
    name: "Bugatti",
    color: "blue",
    info: "lorum dghjg djhge duygeru 3u4ygcd wkeugu wgwerggwe deutkc ",
    price: 95.99,
    img: car,
    location: "united kingdom",
    caption: "Best rate ",
    phoneNumber: "08132703549",
  },
  {
    name: "Bugatti",
    color: "blue",
    info: "lorum dghjg djhge duygeru 3u4ygcd wkeugu wgwerggwe deutkc ",
    price: 95.99,
    img: car,
    location: "united kingdom",
    caption: "Best rate ",
    phoneNumber: "08132703549",
  },
];
export default All_Product;
